baseurl = "https://pzhaonet.github.io/ncov/"
# baseurl = "https://ncov2020.org"
# baseurl = "file:///D:/temp/delete/github/ncov/docs/"
languageCode = "en-us"
title = "nCoV：新型冠状病毒疫情报告"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"

[permalinks]
    post = "/post/:slug/"

[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 10

[[menu.main]]
    name = "疫情概况"
    url = "/intro/"
    weight = 20
[[menu.main]]
    name = "最新图表"
    url = "/fig/"
    weight = 30

[[menu.main]]
    name = "简讯"
    url = "/news/"
    weight = 40

[[menu.main]]
    name = "辟谣"
    url = "/rumors/"
    weight = 50

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "pzhao.org"

